spring.config.import=optional:file:./config/application-local.properties
spring.flyway.locations=classpath:db/migration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/pulso}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jackson.time-zone=America/Sao_Paulo
spring.jpa.open-in-view=false
